In [58]:
import mysql.connector as sql
import pandas as pd
import numpy as np
import datetime

db_connection = sql.connect(host='', database='', user='', password='')
db_cursor = db_connection.cursor()

query = 'SELECT * FROM all_physical'
db_cursor.execute(query)
table_rows = db_cursor.fetchall()
df = pd.DataFrame(table_rows)
data = pd.read_sql(query, db_connection)

In [70]:
# Data size
data.shape

(946719, 53)

In [60]:
data

,Timestamp,FIT101,LIT101,MV101,P101,P102,AIT201,AIT202,AIT203,FIT201,...,P501,P502,PIT501,PIT502,PIT503,FIT601,P601,P602,P603,EVENT
0,28/12/2015 10:00:00 AM,2.427057,522.8467,2,2,1,262.0161,8.396437,328.6337,2.445391,...,2,1,250.8652,1.649953,189.5988,0.000128152,1,1,1,Normal
1,28/12/2015 10:00:01 AM,2.446274,522.886,2,2,1,262.0161,8.396437,328.6337,2.445391,...,2,1,250.8652,1.649953,189.6789,0.000128152,1,1,1,Normal
2,28/12/2015 10:00:02 AM,2.489191,522.8467,2,2,1,262.0161,8.394514,328.6337,2.442316,...,2,1,250.8812,1.649953,189.6789,0.000128152,1,1,1,Normal
3,28/12/2015 10:00:03 AM,2.53435,522.9645,2,2,1,262.0161,8.394514,328.6337,2.442316,...,2,1,250.8812,1.649953,189.6148,0.000128152,1,1,1,Normal
4,28/12/2015 10:00:04 AM,2.56926,523.4748,2,2,1,262.0161,8.394514,328.6337,2.443085,...,2,1,250.8812,1.649953,189.5027,0.000128152,1,1,1,Normal
5,28/12/2015 10:00:05 AM,2.609294,523.8673,2,2,1,262.0161,8.394514,328.6337,2.44411,...,2,1,250.753,1.649953,189.5027,0.000128152,1,1,1,Normal
6,28/12/2015 10:00:06 AM,2.637158,524.1028,2,2,1,262.0161,8.394514,328.6337,2.44411,...,2,1,250.5928,1.649953,189.5027,0.000128152,1,1,1,Normal
7,28/12/2015 10:00:07 AM,2.652211,524.2206,2,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,250.5928,1.649953,189.5027,0.000128152,1,1,1,Normal
8,28/12/2015 10:00:08 AM,2.655735,524.4954,2,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,250.9132,1.649953,189.5027,0.000128152,1,1,1,Normal
9,28/12/2015 10:00:09 AM,2.64997,524.0636,2,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,250.9132,1.649953,189.5668,0.000128152,1,1,1,Normal
10,28/12/2015 10:00:10 AM,2.630433,524.1028,2,2,1,262.0161,8.394514,328.6337,2.441803,...,2,1,251.1055,1.649953,189.8231,0.000128152,1,1,1,Normal
11,28/12/2015 10:00:11 AM,2.621785,523.7496,2,2,1,262.0161,8.391951,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128152,1,1,1,Normal
12,28/12/2015 10:00:12 AM,2.61602,523.4355,2,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128152,1,1,1,Normal
13,28/12/2015 10:00:13 AM,2.599366,523.043,2,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128152,1,1,1,Normal
14,28/12/2015 10:00:14 AM,2.588476,522.729,2,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128152,1,1,1,Normal
15,28/12/2015 10:00:15 AM,2.567979,522.6505,2,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.9994,0.000128152,1,1,1,Normal
16,28/12/2015 10:00:16 AM,2.556769,522.6897,2,2,1,262.0161,8.390669,328.6337,2.441803,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
17,28/12/2015 10:00:17 AM,2.53435,522.6897,2,2,1,262.0161,8.390669,328.6081,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
18,28/12/2015 10:00:18 AM,2.521859,522.6505,2,2,1,262.0161,8.390669,328.3773,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
19,28/12/2015 10:00:19 AM,2.502642,522.6897,2,2,1,262.0161,8.390669,328.3773,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
20,28/12/2015 10:00:20 AM,2.489191,522.729,2,2,1,262.0161,8.390669,328.3773,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
21,28/12/2015 10:00:21 AM,2.473497,522.5327,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
22,28/12/2015 10:00:22 AM,2.458764,522.886,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
23,28/12/2015 10:00:23 AM,2.444031,523.4355,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
24,28/12/2015 10:00:24 AM,2.434744,523.671,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
25,28/12/2015 10:00:25 AM,2.423854,523.7496,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
26,28/12/2015 10:00:26 AM,2.421932,523.8281,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1856,1.649953,189.8872,0.000128152,1,1,1,Normal
27,28/12/2015 10:00:27 AM,2.425776,524.2598,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.1535,1.649953,189.8872,0.000128152,1,1,1,Normal
28,28/12/2015 10:00:28 AM,2.471575,524.1421,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.0414,1.649953,189.8872,0.000128152,1,1,1,Normal
29,28/12/2015 10:00:29 AM,2.527624,524.2598,2,2,1,262.0161,8.390669,328.6337,2.439881,...,2,1,251.0414,1.649953,189.8872,0.000128152,1,1,1,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
946689,28/12/2015 9:59:30 AM,2.436985,522.3364,2,2,1,262.0161,8.388105,328.6593,2.441162,...,2,1,251.2176,1.69801,190.1275,0.0001281517,1,1,1,Normal
946690,28/12/2015 9:59:31 AM,2.428979,521.9832,2,2,1,262.0161,8.388105,328.6593,2.440393,...,2,1,251.2176,1.69801,189.8872,0.0001281517,1,1,1,Normal
946691,28/12/2015 9:59:32 AM,2.427377,521.6691,2,2,1,262.0161,8.388105,328.6593,2.440393,...,2,1,251.0574,1.665972,189.8872,0.0001281517,1,1,1,Normal
946692,28/12/2015 9:59:33 AM,2.436985,521.5906,2,2,1,262.0161,8.388105,328.6593,2.442188,...,2,1,251.0574,1.665972,189.8872,0.0001281517,1,1,1,Normal
946693,28/12/2015 9:59:34 AM,2.47702,521.3944,2,2,1,262.0161,8.388105,328.6593,2.442828,...,2,1,251.0574,1.665972,189.8872,0.0001281517,1,1,1,Normal
946694,28/12/2015 9:59:35 AM,2.528905,521.3159,2,2,1,262.0161,8.388105,328.6593,2.442828,...,2,1,251.3618,1.665972,189.8872,0.0001281517,1,1,1,Normal
946695,28/12/2015 9:59:36 AM,2.559331,521.3944,2,2,1,262.0161,8.388105,328.6593,2.440265,...,2,1,251.3618,1.665972,189.8872,0.0001281517,1,1,1,Normal
946696,28/12/2015 9:59:37 AM,2.595522,521.6691,2,2,1,262.0161,8.388105,328.6593,2.440265,...,2,1,251.3618,1.681991,189.8872,0.0001281517,1,1,1,Normal
946697,28/12/2015 9:59:38 AM,2.62723,521.3159,2,2,1,262.0161,8.388105,328.6593,2.440265,...,2,1,251.3618,1.681991,189.9833,0.0001281517,1,1,1,Normal
946698,28/12/2015 9:59:39 AM,2.659578,521.6691,2,2,1,262.0161,8.388105,328.6593,2.440521,...,2,1,251.0734,1.681991,189.9833,0.0001281517,1,1,1,Normal
946699,28/12/2015 9:59:40 AM,2.669186,521.5121,2,2,1,262.0161,8.388105,328.6593,2.441034,...,2,1,251.0734,1.681991,189.9833,0.0001281517,1,1,1,Normal
946700,28/12/2015 9:59:41 AM,2.657016,521.4729,2,2,1,262.0161,8.390028,328.6593,2.441034,...,2,1,251.0734,1.681991,189.9833,0.0001281517,1,1,1,Normal
946701,28/12/2015 9:59:42 AM,2.633315,521.3159,2,2,1,262.0161,8.39163,328.6593,2.441034,...,2,1,251.0734,1.681991,189.9833,0.0001281517,1,1,1,Normal
946702,28/12/2015 9:59:43 AM,2.628831,521.1589,2,2,1,262.0161,8.39163,328.6593,2.441034,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946703,28/12/2015 9:59:44 AM,2.624027,521.1981,2,2,1,262.0161,8.39163,328.6593,2.441034,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946704,28/12/2015 9:59:45 AM,2.616981,521.2766,2,2,1,262.0161,8.39163,328.6593,2.441034,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946705,28/12/2015 9:59:46 AM,2.602889,521.2766,2,2,1,262.0161,8.39163,328.6593,2.442188,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946706,28/12/2015 9:59:47 AM,2.58111,521.0804,2,2,1,262.0161,8.392271,328.6593,2.442188,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946707,28/12/2015 9:59:48 AM,2.571502,521.5121,2,2,1,262.0161,8.393873,328.6593,2.442188,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946708,28/12/2015 9:59:49 AM,2.552926,521.7869,2,2,1,262.0161,8.393873,328.6593,2.442188,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946709,28/12/2015 9:59:50 AM,2.535311,522.0617,2,2,1,262.0161,8.393873,328.5055,2.444238,...,2,1,251.0734,1.681991,189.8231,0.0001281517,1,1,1,Normal
946710,28/12/2015 9:59:51 AM,2.51225,522.3757,2,2,1,262.0161,8.393873,328.5055,2.444751,...,2,1,251.0734,1.681991,189.8552,0.0001281517,1,1,1,Normal
946711,28/12/2015 9:59:52 AM,2.499119,522.729,2,2,1,262.0161,8.393873,328.5055,2.444751,...,2,1,251.0734,1.681991,189.8552,0.0001281517,1,1,1,Normal
946712,28/12/2015 9:59:53 AM,2.484707,522.4935,2,2,1,262.0161,8.393873,328.5055,2.444751,...,2,1,251.0734,1.681991,189.8552,0.0001281517,1,1,1,Normal
946713,28/12/2015 9:59:54 AM,2.471575,523.1215,2,2,1,262.0161,8.396437,328.5055,2.442956,...,2,1,251.0734,1.681991,189.8552,0.0001281517,1,1,1,Normal
946714,28/12/2015 9:59:55 AM,2.460366,523.043,2,2,1,262.0161,8.396437,328.5055,2.442316,...,2,1,250.8171,1.778105,189.8552,0.0001281517,1,1,1,Normal
946715,28/12/2015 9:59:56 AM,2.448836,522.9645,2,2,1,262.0161,8.396437,328.5055,2.442316,...,2,1,250.8171,1.778105,189.5027,0.0001281517,1,1,1,Normal
946716,28/12/2015 9:59:57 AM,2.434744,522.886,2,2,1,262.0161,8.396437,328.6337,2.444879,...,2,1,250.8171,1.778105,189.5027,0.0001281517,1,1,1,Normal
946717,28/12/2015 9:59:58 AM,2.428338,522.9252,2,2,1,262.0161,8.396437,328.6337,2.445391,...,2,1,250.8171,1.649953,189.5027,0.0001281517,1,1,1,Normal
946718,28/12/2015 9:59:59 AM,2.427057,522.8467,2,2,1,262.0161,8.396437,328.6337,2.445391,...,2,1,250.8652,1.649953,189.5988,0.0001281517,1,1,1,Normal

In [61]:
# List of columns
list(data)

['Timestamp',
 'FIT101',
 'LIT101',
 'MV101',
 'P101',
 'P102',
 'AIT201',
 'AIT202',
 'AIT203',
 'FIT201',
 'MV201',
 'P201',
 'P202',
 'P203',
 'P204',
 'P205',
 'P206',
 'DPIT301',
 'FIT301',
 'LIT301',
 'MV301',
 'MV302',
 'MV303',
 'MV304',
 'P301',
 'P302',
 'AIT401',
 'AIT402',
 'FIT401',
 'LIT401',
 'P401',
 'P402',
 'P403',
 'P404',
 'UV401',
 'AIT501',
 'AIT502',
 'AIT503',
 'AIT504',
 'FIT501',
 'FIT502',
 'FIT503',
 'FIT504',
 'P501',
 'P502',
 'PIT501',
 'PIT502',
 'PIT503',
 'FIT601',
 'P601',
 'P602',
 'P603',
 'EVENT']

In [62]:
# No missing values in the data
data.isnull().any()

Timestamp    False
FIT101       False
LIT101       False
MV101        False
P101         False
P102         False
AIT201       False
AIT202       False
AIT203       False
FIT201       False
MV201        False
P201         False
P202         False
P203         False
P204         False
P205         False
P206         False
DPIT301      False
FIT301       False
LIT301       False
MV301        False
MV302        False
MV303        False
MV304        False
P301         False
P302         False
AIT401       False
AIT402       False
FIT401       False
LIT401       False
P401         False
P402         False
P403         False
P404         False
UV401        False
AIT501       False
AIT502       False
AIT503       False
AIT504       False
FIT501       False
FIT502       False
FIT503       False
FIT504       False
P501         False
P502         False
PIT501       False
PIT502       False
PIT503       False
FIT601       False
P601         False
P602         False
P603         False
EVENT        False
dtype: bool

In [63]:
# Data type
data.dtypes

Timestamp    object
FIT101       object
LIT101       object
MV101        object
P101         object
P102         object
AIT201       object
AIT202       object
AIT203       object
FIT201       object
MV201        object
P201         object
P202         object
P203         object
P204         object
P205         object
P206         object
DPIT301      object
FIT301       object
LIT301       object
MV301        object
MV302        object
MV303        object
MV304        object
P301         object
P302         object
AIT401       object
AIT402       object
FIT401       object
LIT401       object
P401         object
P402         object
P403         object
P404         object
UV401        object
AIT501       object
AIT502       object
AIT503       object
AIT504       object
FIT501       object
FIT502       object
FIT503       object
FIT504       object
P501         object
P502         object
PIT501       object
PIT502       object
PIT503       object
FIT601       object
P601         object
P602         object
P603         object
EVENT        object
dtype: object

In [66]:
for i in range(0, len(data)):
    data.iloc[i]['Timestamp'] = dt.datetime.strptime(data.iloc[i]['Timestamp'],' %d/%m/%Y %H:%M:%S %p')

In [78]:
import datetime as dt

for i in range(0, len(data)-1):
    if data.iloc[i+1]['Timestamp'] != data.iloc[i]['Timestamp'] + dt.timedelta(seconds=1):
        print(data.iloc[i]['Timestamp'], data.iloc[i+1]['Timestamp'])
# Two Missing time periods:
# 2015-12-31 09:00:36 to 2015-12-31 09:01:58
# 2016-01-02 02:59:59 to 2015-12-22 04:00:00

2015-12-28 12:59:59 2015-12-28 01:00:00
2015-12-28 11:59:59 2015-12-29 12:00:00
2015-12-29 12:59:59 2015-12-29 01:00:00
2015-12-29 12:59:59 2015-12-29 01:00:00
2015-12-29 11:59:59 2015-12-30 12:00:00
2015-12-30 12:59:59 2015-12-30 01:00:00
2015-12-30 12:59:59 2015-12-30 01:00:00
2015-12-30 11:59:59 2015-12-31 12:00:00
2015-12-31 12:59:59 2015-12-31 01:00:00
2015-12-31 12:59:59 2015-12-31 01:00:00
2015-12-31 09:00:36 2015-12-31 09:01:58
2015-12-31 11:59:59 2016-01-01 12:00:00
2016-01-01 12:59:59 2016-01-01 01:00:00
2016-01-01 12:59:59 2016-01-01 01:00:00
2016-01-01 11:59:59 2016-01-02 12:00:00
2016-01-02 12:59:59 2016-01-02 01:00:00
2016-01-02 12:59:59 2016-01-02 01:00:00
2016-01-02 02:59:59 2015-12-22 04:00:00
2015-12-22 11:59:59 2015-12-23 12:00:00
2015-12-23 12:59:59 2015-12-23 01:00:00
2015-12-23 12:59:59 2015-12-23 01:00:00
2015-12-23 11:59:59 2015-12-24 12:00:00
2015-12-24 12:59:59 2015-12-24 01:00:00
2015-12-24 12:59:59 2015-12-24 01:00:00
2015-12-24 11:59:59 2015-12-25 12:00:00
2015-12-25 12:59:59 2015-12-25 01:00:00
2015-12-25 12:59:59 2015-12-25 01:00:00
2015-12-25 11:59:59 2015-12-26 12:00:00
2015-12-26 12:59:59 2015-12-26 01:00:00
2015-12-26 12:59:59 2015-12-26 01:00:00
2015-12-26 11:59:59 2015-12-27 12:00:00
2015-12-27 12:59:59 2015-12-27 01:00:00
2015-12-27 12:59:59 2015-12-27 01:00:00
2015-12-27 11:59:59 2015-12-28 12:00:00
2015-12-28 12:59:59 2015-12-28 01:00:00